/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.property.controller;import cn.zhuatech.property.common.ApiResponse;import cn.zhuatech.property.service.TenantMoveInReadinessService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                          */
@RestController @RequestMapping("/api/enterprise/property")public class TenantMoveInReadinessController{private final TenantMoveInReadinessService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                     */
public TenantMoveInReadinessController(TenantMoveInReadinessService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/tenant-move-in")public ApiResponse<TenantMoveInReadinessService.Assessment>assess(@Valid @RequestBody TenantMoveInReadinessService.Request request){return ApiResponse.ok(service.assess(request));}}
