/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.property.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                 */
class TenantMoveInReadinessServiceTest{private final TenantMoveInReadinessService service=new TenantMoveInReadinessService();/**
                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                              */
@Test void approvesReadyMoveIn(){var r=service.assess(new TenantMoveInReadinessService.Request("L1",true,true,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(TenantMoveInReadinessService.Decision.MOVE_IN);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@Test void blocksCommercialAndSafetyGaps(){var r=service.assess(new TenantMoveInReadinessService.Request("L2",false,false,false,false,false,true,true,true,true));assertThat(r.blockers()).hasSize(5);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Test void reviewsOperationalHandover(){var r=service.assess(new TenantMoveInReadinessService.Request("L3",true,true,true,true,true,false,false,false,false));assertThat(r.actions()).hasSize(4);}}
